### ISSUE TITLE
ts_setup.py

### ISSUE THREAD

**Issue by titasroy89** [elliot-hughes/hcal_teststand_scripts#5]
This shouldn't happen:

```
[tiroy@vmepc-e1x07-06-01 hcal_teststand_scripts]$ python ts_setup.py
> Setting up the 904 teststand ...
> Setting up the AMC13 ...
> Can ping T1.
> Can ping T2.
> [!!] Can't fetch FW versions.
> Setting up the uHTRs ...
> Setting up uHTR in slot 12 ...
> uHTR set up.
> [!!] Set up aborted.
```

Fix it, Tote!

**Comment by awhitbeck** [comment]
Hi titas, 

I think this problem is not with the code, but with your local setup.  You should rerun that install.py script:

python install.py 904

and then the ts_setup.py script should work fine.  I also had this problem and only realized yesterday, while talking with tote that this was the solution.  Can you give it a try and see.  If so, close this issue. 

Andrew

**Comment by elliot-hughes** [comment]
While Andrew makes a good point, there was a also a small bug allowing the uHTRs to be set up even when something went wrong with the AMC13. This is fixed with [this line](https://github.com/Teststandees/hcal_teststand_scripts/blob/master/ts_setup.py#L99) in `ts_setup.py`.
